services:
  postgres:
    build:
      context: .
      dockerfile: my-book-collection.dockerfile
    image: "pg-my-book-collection"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
       - postgres_books:/var/lib/postgresql/data
    ports:
      - "5401:5432"
    restart: unless-stopped
volumes:
    postgres_books:
      external: true